//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ActionDispatcher
{
    [Serializable]
    public class SendActionStateRequest : Message
    {
        public const string k_RosMessageName = "action_dispatcher/SendActionState";
        public override string RosMessageName => k_RosMessageName;

        public ActionDispatcherStateMsg state;

        public SendActionStateRequest()
        {
            this.state = new ActionDispatcherStateMsg();
        }

        public SendActionStateRequest(ActionDispatcherStateMsg state)
        {
            this.state = state;
        }

        public static SendActionStateRequest Deserialize(MessageDeserializer deserializer) => new SendActionStateRequest(deserializer);

        private SendActionStateRequest(MessageDeserializer deserializer)
        {
            this.state = ActionDispatcherStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "SendActionStateRequest: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
