//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ActionDispatcher
{
    [Serializable]
    public class SendManipulationPlanFeedbackRequest : Message
    {
        public const string k_RosMessageName = "action_dispatcher/SendManipulationPlanFeedback";
        public override string RosMessageName => k_RosMessageName;

        public Manipulation.ManipulationPlanRequestMsg current_action;

        public SendManipulationPlanFeedbackRequest()
        {
            this.current_action = new Manipulation.ManipulationPlanRequestMsg();
        }

        public SendManipulationPlanFeedbackRequest(Manipulation.ManipulationPlanRequestMsg current_action)
        {
            this.current_action = current_action;
        }

        public static SendManipulationPlanFeedbackRequest Deserialize(MessageDeserializer deserializer) => new SendManipulationPlanFeedbackRequest(deserializer);

        private SendManipulationPlanFeedbackRequest(MessageDeserializer deserializer)
        {
            this.current_action = Manipulation.ManipulationPlanRequestMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.current_action);
        }

        public override string ToString()
        {
            return "SendManipulationPlanFeedbackRequest: " +
            "\ncurrent_action: " + current_action.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
