//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.LanguageModel
{
    [Serializable]
    public class QueryLanguageModelResponse : Message
    {
        public const string k_RosMessageName = "language_model/QueryLanguageModel";
        public override string RosMessageName => k_RosMessageName;

        public string response;

        public QueryLanguageModelResponse()
        {
            this.response = "";
        }

        public QueryLanguageModelResponse(string response)
        {
            this.response = response;
        }

        public static QueryLanguageModelResponse Deserialize(MessageDeserializer deserializer) => new QueryLanguageModelResponse(deserializer);

        private QueryLanguageModelResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.response);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.response);
        }

        public override string ToString()
        {
            return "QueryLanguageModelResponse: " +
            "\nresponse: " + response.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
