//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.LanguageModel
{
    [Serializable]
    public class QueryLanguageModelRequest : Message
    {
        public const string k_RosMessageName = "language_model/QueryLanguageModel";
        public override string RosMessageName => k_RosMessageName;

        public PromptMsg prompt;

        public QueryLanguageModelRequest()
        {
            this.prompt = new PromptMsg();
        }

        public QueryLanguageModelRequest(PromptMsg prompt)
        {
            this.prompt = prompt;
        }

        public static QueryLanguageModelRequest Deserialize(MessageDeserializer deserializer) => new QueryLanguageModelRequest(deserializer);

        private QueryLanguageModelRequest(MessageDeserializer deserializer)
        {
            this.prompt = PromptMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.prompt);
        }

        public override string ToString()
        {
            return "QueryLanguageModelRequest: " +
            "\nprompt: " + prompt.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
