//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RuleGenerator
{
    [Serializable]
    public class GetUserApprovalResponse : Message
    {
        public const string k_RosMessageName = "rule_generator/GetUserApproval";
        public override string RosMessageName => k_RosMessageName;

        public UserApprovalResponseMsg response;

        public GetUserApprovalResponse()
        {
            this.response = new UserApprovalResponseMsg();
        }

        public GetUserApprovalResponse(UserApprovalResponseMsg response)
        {
            this.response = response;
        }

        public static GetUserApprovalResponse Deserialize(MessageDeserializer deserializer) => new GetUserApprovalResponse(deserializer);

        private GetUserApprovalResponse(MessageDeserializer deserializer)
        {
            this.response = UserApprovalResponseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.response);
        }

        public override string ToString()
        {
            return "GetUserApprovalResponse: " +
            "\nresponse: " + response.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
