//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ActionDispatcher
{
    [Serializable]
    public class DispatchActionsResult : Message
    {
        public const string k_RosMessageName = "action_dispatcher/DispatchActions";
        public override string RosMessageName => k_RosMessageName;

        // result 
        public Moveit.MoveItErrorCodesMsg error_code;

        public DispatchActionsResult()
        {
            this.error_code = new Moveit.MoveItErrorCodesMsg();
        }

        public DispatchActionsResult(Moveit.MoveItErrorCodesMsg error_code)
        {
            this.error_code = error_code;
        }

        public static DispatchActionsResult Deserialize(MessageDeserializer deserializer) => new DispatchActionsResult(deserializer);

        private DispatchActionsResult(MessageDeserializer deserializer)
        {
            this.error_code = Moveit.MoveItErrorCodesMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.error_code);
        }

        public override string ToString()
        {
            return "DispatchActionsResult: " +
            "\nerror_code: " + error_code.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
