//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ActionDispatcher
{
    [Serializable]
    public class DispatchActionsGoal : Message
    {
        public const string k_RosMessageName = "action_dispatcher/DispatchActions";
        public override string RosMessageName => k_RosMessageName;

        // goal for the manipulation action
        public Manipulation.ManipulationPlanRequestMsg[] actions;

        public DispatchActionsGoal()
        {
            this.actions = new Manipulation.ManipulationPlanRequestMsg[0];
        }

        public DispatchActionsGoal(Manipulation.ManipulationPlanRequestMsg[] actions)
        {
            this.actions = actions;
        }

        public static DispatchActionsGoal Deserialize(MessageDeserializer deserializer) => new DispatchActionsGoal(deserializer);

        private DispatchActionsGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.actions, Manipulation.ManipulationPlanRequestMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.actions);
            serializer.Write(this.actions);
        }

        public override string ToString()
        {
            return "DispatchActionsGoal: " +
            "\nactions: " + System.String.Join(", ", actions.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
