//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Perception
{
    [Serializable]
    public class GetDetectionClassesRequest : Message
    {
        public const string k_RosMessageName = "perception/GetDetectionClasses";
        public override string RosMessageName => k_RosMessageName;


        public GetDetectionClassesRequest()
        {
        }
        public static GetDetectionClassesRequest Deserialize(MessageDeserializer deserializer) => new GetDetectionClassesRequest(deserializer);

        private GetDetectionClassesRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetDetectionClassesRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
