//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RuleGenerator
{
    [Serializable]
    public class RuleGeneratorStateMsg : Message
    {
        public const string k_RosMessageName = "rule_generator/RuleGeneratorState";
        public override string RosMessageName => k_RosMessageName;

        public const int IDLE = 0;
        public const int GENERATE_RULE = 1;
        public const int WAIT_FOR_APPROVAL = 2;
        public const int WAIT_FOR_FEEDBACK = 3;
        public const int ADD_RULE = 4;
        public const int DONE = 5;
        public int state;

        public RuleGeneratorStateMsg()
        {
            this.state = 0;
        }

        public RuleGeneratorStateMsg(int state)
        {
            this.state = state;
        }

        public static RuleGeneratorStateMsg Deserialize(MessageDeserializer deserializer) => new RuleGeneratorStateMsg(deserializer);

        private RuleGeneratorStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "RuleGeneratorStateMsg: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
