//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RuleGenerator
{
    [Serializable]
    public class UserFeedbackMsg : Message
    {
        public const string k_RosMessageName = "rule_generator/UserFeedback";
        public override string RosMessageName => k_RosMessageName;

        public string speech_command;
        public string speech_command_feedback;

        public UserFeedbackMsg()
        {
            this.speech_command = "";
            this.speech_command_feedback = "";
        }

        public UserFeedbackMsg(string speech_command, string speech_command_feedback)
        {
            this.speech_command = speech_command;
            this.speech_command_feedback = speech_command_feedback;
        }

        public static UserFeedbackMsg Deserialize(MessageDeserializer deserializer) => new UserFeedbackMsg(deserializer);

        private UserFeedbackMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.speech_command);
            deserializer.Read(out this.speech_command_feedback);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.speech_command);
            serializer.Write(this.speech_command_feedback);
        }

        public override string ToString()
        {
            return "UserFeedbackMsg: " +
            "\nspeech_command: " + speech_command.ToString() +
            "\nspeech_command_feedback: " + speech_command_feedback.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
