//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RuleGenerator
{
    [Serializable]
    public class UserApprovalResponseMsg : Message
    {
        public const string k_RosMessageName = "rule_generator/UserApprovalResponse";
        public override string RosMessageName => k_RosMessageName;

        public const int APPROVED = 0;
        public const int FEEDBACK = 1;
        public const int DELETE = 2;
        public int response;

        public UserApprovalResponseMsg()
        {
            this.response = 0;
        }

        public UserApprovalResponseMsg(int response)
        {
            this.response = response;
        }

        public static UserApprovalResponseMsg Deserialize(MessageDeserializer deserializer) => new UserApprovalResponseMsg(deserializer);

        private UserApprovalResponseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.response);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.response);
        }

        public override string ToString()
        {
            return "UserApprovalResponseMsg: " +
            "\nresponse: " + response.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
