//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Manipulation
{
    [Serializable]
    public class ManipulationPlanResponseMsg : Message
    {
        public const string k_RosMessageName = "manipulation/ManipulationPlanResponse";
        public override string RosMessageName => k_RosMessageName;

        //  Manipulation plan solution response
        public MoveitTaskConstructor.SolutionMsg solution;
        //  Reason for error
        public Moveit.MoveItErrorCodesMsg error_code;

        public ManipulationPlanResponseMsg()
        {
            this.solution = new MoveitTaskConstructor.SolutionMsg();
            this.error_code = new Moveit.MoveItErrorCodesMsg();
        }

        public ManipulationPlanResponseMsg(MoveitTaskConstructor.SolutionMsg solution, Moveit.MoveItErrorCodesMsg error_code)
        {
            this.solution = solution;
            this.error_code = error_code;
        }

        public static ManipulationPlanResponseMsg Deserialize(MessageDeserializer deserializer) => new ManipulationPlanResponseMsg(deserializer);

        private ManipulationPlanResponseMsg(MessageDeserializer deserializer)
        {
            this.solution = MoveitTaskConstructor.SolutionMsg.Deserialize(deserializer);
            this.error_code = Moveit.MoveItErrorCodesMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.solution);
            serializer.Write(this.error_code);
        }

        public override string ToString()
        {
            return "ManipulationPlanResponseMsg: " +
            "\nsolution: " + solution.ToString() +
            "\nerror_code: " + error_code.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
