//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RuleMonitor
{
    [Serializable]
    public class TriggerTypeMsg : Message
    {
        public const string k_RosMessageName = "rule_monitor/TriggerType";
        public override string RosMessageName => k_RosMessageName;

        public const int NONE = 0;
        public const int ZONE = 1;
        public const int TIMER = 2;
        public int type;

        public TriggerTypeMsg()
        {
            this.type = 0;
        }

        public TriggerTypeMsg(int type)
        {
            this.type = type;
        }

        public static TriggerTypeMsg Deserialize(MessageDeserializer deserializer) => new TriggerTypeMsg(deserializer);

        private TriggerTypeMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.type);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.type);
        }

        public override string ToString()
        {
            return "TriggerTypeMsg: " +
            "\ntype: " + type.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
