//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SceneGraph
{
    [Serializable]
    public class UnityRelationshipMsg : Message
    {
        public const string k_RosMessageName = "scene_graph/UnityRelationship";
        public override string RosMessageName => k_RosMessageName;

        public string zone;
        public string relationship;
        public string[] node_objects;
        public Geometry.PoseMsg pose;
        public Shape.SolidPrimitiveMsg primitive;

        public UnityRelationshipMsg()
        {
            this.zone = "";
            this.relationship = "";
            this.node_objects = new string[0];
            this.pose = new Geometry.PoseMsg();
            this.primitive = new Shape.SolidPrimitiveMsg();
        }

        public UnityRelationshipMsg(string zone, string relationship, string[] node_objects, Geometry.PoseMsg pose, Shape.SolidPrimitiveMsg primitive)
        {
            this.zone = zone;
            this.relationship = relationship;
            this.node_objects = node_objects;
            this.pose = pose;
            this.primitive = primitive;
        }

        public static UnityRelationshipMsg Deserialize(MessageDeserializer deserializer) => new UnityRelationshipMsg(deserializer);

        private UnityRelationshipMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.zone);
            deserializer.Read(out this.relationship);
            deserializer.Read(out this.node_objects, deserializer.ReadLength());
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.primitive = Shape.SolidPrimitiveMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.zone);
            serializer.Write(this.relationship);
            serializer.WriteLength(this.node_objects);
            serializer.Write(this.node_objects);
            serializer.Write(this.pose);
            serializer.Write(this.primitive);
        }

        public override string ToString()
        {
            return "UnityRelationshipMsg: " +
            "\nzone: " + zone.ToString() +
            "\nrelationship: " + relationship.ToString() +
            "\nnode_objects: " + System.String.Join(", ", node_objects.ToList()) +
            "\npose: " + pose.ToString() +
            "\nprimitive: " + primitive.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
