//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SceneGraph
{
    [Serializable]
    public class UnityRelationshipsMsg : Message
    {
        public const string k_RosMessageName = "scene_graph/UnityRelationships";
        public override string RosMessageName => k_RosMessageName;

        public UnityRelationshipMsg[] relationships;

        public UnityRelationshipsMsg()
        {
            this.relationships = new UnityRelationshipMsg[0];
        }

        public UnityRelationshipsMsg(UnityRelationshipMsg[] relationships)
        {
            this.relationships = relationships;
        }

        public static UnityRelationshipsMsg Deserialize(MessageDeserializer deserializer) => new UnityRelationshipsMsg(deserializer);

        private UnityRelationshipsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.relationships, UnityRelationshipMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.relationships);
            serializer.Write(this.relationships);
        }

        public override string ToString()
        {
            return "UnityRelationshipsMsg: " +
            "\nrelationships: " + System.String.Join(", ", relationships.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
