//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ActionDispatcher
{
    [Serializable]
    public class ActionDispatcherStateMsg : Message
    {
        public const string k_RosMessageName = "action_dispatcher/ActionDispatcherState";
        public override string RosMessageName => k_RosMessageName;

        public const int IDLE = 0;
        public const int PLANNING = 1;
        public const int SEND_PLAN = 2;
        public const int MONITOR_EXECUTION = 3;
        public const int RECOVERY = 4;
        public int state;

        public ActionDispatcherStateMsg()
        {
            this.state = 0;
        }

        public ActionDispatcherStateMsg(int state)
        {
            this.state = state;
        }

        public static ActionDispatcherStateMsg Deserialize(MessageDeserializer deserializer) => new ActionDispatcherStateMsg(deserializer);

        private ActionDispatcherStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "ActionDispatcherStateMsg: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
