//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ActionDispatcher
{
    [Serializable]
    public class DisplaySolutionMsg : Message
    {
        public const string k_RosMessageName = "action_dispatcher/DisplaySolution";
        public override string RosMessageName => k_RosMessageName;

        //  id of generating task
        public sbyte task_id;
        public SceneSetupMsg start_scene;
        //  Trajectory display stuff
        public MinimalSubTrajectoryMsg[] sub_trajectories;

        public DisplaySolutionMsg()
        {
            this.task_id = 0;
            this.start_scene = new SceneSetupMsg();
            this.sub_trajectories = new MinimalSubTrajectoryMsg[0];
        }

        public DisplaySolutionMsg(sbyte task_id, SceneSetupMsg start_scene, MinimalSubTrajectoryMsg[] sub_trajectories)
        {
            this.task_id = task_id;
            this.start_scene = start_scene;
            this.sub_trajectories = sub_trajectories;
        }

        public static DisplaySolutionMsg Deserialize(MessageDeserializer deserializer) => new DisplaySolutionMsg(deserializer);

        private DisplaySolutionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.task_id);
            this.start_scene = SceneSetupMsg.Deserialize(deserializer);
            deserializer.Read(out this.sub_trajectories, MinimalSubTrajectoryMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.task_id);
            serializer.Write(this.start_scene);
            serializer.WriteLength(this.sub_trajectories);
            serializer.Write(this.sub_trajectories);
        }

        public override string ToString()
        {
            return "DisplaySolutionMsg: " +
            "\ntask_id: " + task_id.ToString() +
            "\nstart_scene: " + start_scene.ToString() +
            "\nsub_trajectories: " + System.String.Join(", ", sub_trajectories.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
