//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ActionDispatcher
{
    [Serializable]
    public class JointTrajectoryPositionsMsg : Message
    {
        public const string k_RosMessageName = "action_dispatcher/JointTrajectoryPositions";
        public override string RosMessageName => k_RosMessageName;

        public double[] positions;

        public JointTrajectoryPositionsMsg()
        {
            this.positions = new double[0];
        }

        public JointTrajectoryPositionsMsg(double[] positions)
        {
            this.positions = positions;
        }

        public static JointTrajectoryPositionsMsg Deserialize(MessageDeserializer deserializer) => new JointTrajectoryPositionsMsg(deserializer);

        private JointTrajectoryPositionsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.positions, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.positions);
            serializer.Write(this.positions);
        }

        public override string ToString()
        {
            return "JointTrajectoryPositionsMsg: " +
            "\npositions: " + System.String.Join(", ", positions.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
