//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ActionDispatcher
{
    [Serializable]
    public class MinimalSubTrajectoryMsg : Message
    {
        public const string k_RosMessageName = "action_dispatcher/MinimalSubTrajectory";
        public override string RosMessageName => k_RosMessageName;

        public const sbyte NONE = 0;
        public const sbyte OBJECT_ATTACHED = 1;
        public const sbyte OBJECT_DETACHED = 2;
        public sbyte object_state_change;
        public string[] joint_names;
        public JointTrajectoryPositionsMsg[] positions;

        public MinimalSubTrajectoryMsg()
        {
            this.object_state_change = 0;
            this.joint_names = new string[0];
            this.positions = new JointTrajectoryPositionsMsg[0];
        }

        public MinimalSubTrajectoryMsg(sbyte object_state_change, string[] joint_names, JointTrajectoryPositionsMsg[] positions)
        {
            this.object_state_change = object_state_change;
            this.joint_names = joint_names;
            this.positions = positions;
        }

        public static MinimalSubTrajectoryMsg Deserialize(MessageDeserializer deserializer) => new MinimalSubTrajectoryMsg(deserializer);

        private MinimalSubTrajectoryMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.object_state_change);
            deserializer.Read(out this.joint_names, deserializer.ReadLength());
            deserializer.Read(out this.positions, JointTrajectoryPositionsMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.object_state_change);
            serializer.WriteLength(this.joint_names);
            serializer.Write(this.joint_names);
            serializer.WriteLength(this.positions);
            serializer.Write(this.positions);
        }

        public override string ToString()
        {
            return "MinimalSubTrajectoryMsg: " +
            "\nobject_state_change: " + object_state_change.ToString() +
            "\njoint_names: " + System.String.Join(", ", joint_names.ToList()) +
            "\npositions: " + System.String.Join(", ", positions.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
