//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ActionDispatcher
{
    [Serializable]
    public class SceneSetupMsg : Message
    {
        public const string k_RosMessageName = "action_dispatcher/SceneSetup";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseStampedMsg[] involved_locations;
        public Geometry.PoseStampedMsg current_attached_object_start_pose;
        public Geometry.PoseStampedMsg future_attached_object_start_pose;
        public Geometry.PoseStampedMsg future_placed_object_end_pose;

        public SceneSetupMsg()
        {
            this.involved_locations = new Geometry.PoseStampedMsg[0];
            this.current_attached_object_start_pose = new Geometry.PoseStampedMsg();
            this.future_attached_object_start_pose = new Geometry.PoseStampedMsg();
            this.future_placed_object_end_pose = new Geometry.PoseStampedMsg();
        }

        public SceneSetupMsg(Geometry.PoseStampedMsg[] involved_locations, Geometry.PoseStampedMsg current_attached_object_start_pose, Geometry.PoseStampedMsg future_attached_object_start_pose, Geometry.PoseStampedMsg future_placed_object_end_pose)
        {
            this.involved_locations = involved_locations;
            this.current_attached_object_start_pose = current_attached_object_start_pose;
            this.future_attached_object_start_pose = future_attached_object_start_pose;
            this.future_placed_object_end_pose = future_placed_object_end_pose;
        }

        public static SceneSetupMsg Deserialize(MessageDeserializer deserializer) => new SceneSetupMsg(deserializer);

        private SceneSetupMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.involved_locations, Geometry.PoseStampedMsg.Deserialize, deserializer.ReadLength());
            this.current_attached_object_start_pose = Geometry.PoseStampedMsg.Deserialize(deserializer);
            this.future_attached_object_start_pose = Geometry.PoseStampedMsg.Deserialize(deserializer);
            this.future_placed_object_end_pose = Geometry.PoseStampedMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.involved_locations);
            serializer.Write(this.involved_locations);
            serializer.Write(this.current_attached_object_start_pose);
            serializer.Write(this.future_attached_object_start_pose);
            serializer.Write(this.future_placed_object_end_pose);
        }

        public override string ToString()
        {
            return "SceneSetupMsg: " +
            "\ninvolved_locations: " + System.String.Join(", ", involved_locations.ToList()) +
            "\ncurrent_attached_object_start_pose: " + current_attached_object_start_pose.ToString() +
            "\nfuture_attached_object_start_pose: " + future_attached_object_start_pose.ToString() +
            "\nfuture_placed_object_end_pose: " + future_placed_object_end_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
