//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RuleMonitor
{
    [Serializable]
    public class GetRuleDescriptionRequest : Message
    {
        public const string k_RosMessageName = "rule_monitor/GetRuleDescription";
        public override string RosMessageName => k_RosMessageName;

        public string name;

        public GetRuleDescriptionRequest()
        {
            this.name = "";
        }

        public GetRuleDescriptionRequest(string name)
        {
            this.name = name;
        }

        public static GetRuleDescriptionRequest Deserialize(MessageDeserializer deserializer) => new GetRuleDescriptionRequest(deserializer);

        private GetRuleDescriptionRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "GetRuleDescriptionRequest: " +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
