//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RuleMonitor
{
    [Serializable]
    public class SendActiveRulesResponse : Message
    {
        public const string k_RosMessageName = "rule_monitor/SendActiveRules";
        public override string RosMessageName => k_RosMessageName;


        public SendActiveRulesResponse()
        {
        }
        public static SendActiveRulesResponse Deserialize(MessageDeserializer deserializer) => new SendActiveRulesResponse(deserializer);

        private SendActiveRulesResponse(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "SendActiveRulesResponse: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
