//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RuleMonitor
{
    [Serializable]
    public class SendActiveRulesRequest : Message
    {
        public const string k_RosMessageName = "rule_monitor/SendActiveRules";
        public override string RosMessageName => k_RosMessageName;

        public ActiveRulesMsg active_rules;

        public SendActiveRulesRequest()
        {
            this.active_rules = new ActiveRulesMsg();
        }

        public SendActiveRulesRequest(ActiveRulesMsg active_rules)
        {
            this.active_rules = active_rules;
        }

        public static SendActiveRulesRequest Deserialize(MessageDeserializer deserializer) => new SendActiveRulesRequest(deserializer);

        private SendActiveRulesRequest(MessageDeserializer deserializer)
        {
            this.active_rules = ActiveRulesMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.active_rules);
        }

        public override string ToString()
        {
            return "SendActiveRulesRequest: " +
            "\nactive_rules: " + active_rules.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
