//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RuleMonitor
{
    [Serializable]
    public class UpdateRuleRequest : Message
    {
        public const string k_RosMessageName = "rule_monitor/UpdateRule";
        public override string RosMessageName => k_RosMessageName;

        public RuleMsg rule;

        public UpdateRuleRequest()
        {
            this.rule = new RuleMsg();
        }

        public UpdateRuleRequest(RuleMsg rule)
        {
            this.rule = rule;
        }

        public static UpdateRuleRequest Deserialize(MessageDeserializer deserializer) => new UpdateRuleRequest(deserializer);

        private UpdateRuleRequest(MessageDeserializer deserializer)
        {
            this.rule = RuleMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.rule);
        }

        public override string ToString()
        {
            return "UpdateRuleRequest: " +
            "\nrule: " + rule.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
