//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.LanguageModel
{
    [Serializable]
    public class ContentItemsMsg : Message
    {
        public const string k_RosMessageName = "language_model/ContentItems";
        public override string RosMessageName => k_RosMessageName;

        public ContentItemMsg[] content_items;

        public ContentItemsMsg()
        {
            this.content_items = new ContentItemMsg[0];
        }

        public ContentItemsMsg(ContentItemMsg[] content_items)
        {
            this.content_items = content_items;
        }

        public static ContentItemsMsg Deserialize(MessageDeserializer deserializer) => new ContentItemsMsg(deserializer);

        private ContentItemsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.content_items, ContentItemMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.content_items);
            serializer.Write(this.content_items);
        }

        public override string ToString()
        {
            return "ContentItemsMsg: " +
            "\ncontent_items: " + System.String.Join(", ", content_items.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
