//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.LanguageModel
{
    [Serializable]
    public class ContentItemMsg : Message
    {
        public const string k_RosMessageName = "language_model/ContentItem";
        public override string RosMessageName => k_RosMessageName;

        public string type;
        public string text;

        public ContentItemMsg()
        {
            this.type = "";
            this.text = "";
        }

        public ContentItemMsg(string type, string text)
        {
            this.type = type;
            this.text = text;
        }

        public static ContentItemMsg Deserialize(MessageDeserializer deserializer) => new ContentItemMsg(deserializer);

        private ContentItemMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.type);
            deserializer.Read(out this.text);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.type);
            serializer.Write(this.text);
        }

        public override string ToString()
        {
            return "ContentItemMsg: " +
            "\ntype: " + type.ToString() +
            "\ntext: " + text.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
