//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.LanguageModel
{
    [Serializable]
    public class PromptMsg : Message
    {
        public const string k_RosMessageName = "language_model/Prompt";
        public override string RosMessageName => k_RosMessageName;

        public string primary_role;
        public string primary_role_content;
        public string secondary_role;
        public ContentItemsMsg secondary_role_content;

        public PromptMsg()
        {
            this.primary_role = "";
            this.primary_role_content = "";
            this.secondary_role = "";
            this.secondary_role_content = new ContentItemsMsg();
        }

        public PromptMsg(string primary_role, string primary_role_content, string secondary_role, ContentItemsMsg secondary_role_content)
        {
            this.primary_role = primary_role;
            this.primary_role_content = primary_role_content;
            this.secondary_role = secondary_role;
            this.secondary_role_content = secondary_role_content;
        }

        public static PromptMsg Deserialize(MessageDeserializer deserializer) => new PromptMsg(deserializer);

        private PromptMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.primary_role);
            deserializer.Read(out this.primary_role_content);
            deserializer.Read(out this.secondary_role);
            this.secondary_role_content = ContentItemsMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.primary_role);
            serializer.Write(this.primary_role_content);
            serializer.Write(this.secondary_role);
            serializer.Write(this.secondary_role_content);
        }

        public override string ToString()
        {
            return "PromptMsg: " +
            "\nprimary_role: " + primary_role.ToString() +
            "\nprimary_role_content: " + primary_role_content.ToString() +
            "\nsecondary_role: " + secondary_role.ToString() +
            "\nsecondary_role_content: " + secondary_role_content.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
