//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Manipulation
{
    [Serializable]
    public class GetManipulationPlanRequest : Message
    {
        public const string k_RosMessageName = "manipulation/GetManipulationPlan";
        public override string RosMessageName => k_RosMessageName;

        public ManipulationPlanRequestMsg manipulation_plan_request;

        public GetManipulationPlanRequest()
        {
            this.manipulation_plan_request = new ManipulationPlanRequestMsg();
        }

        public GetManipulationPlanRequest(ManipulationPlanRequestMsg manipulation_plan_request)
        {
            this.manipulation_plan_request = manipulation_plan_request;
        }

        public static GetManipulationPlanRequest Deserialize(MessageDeserializer deserializer) => new GetManipulationPlanRequest(deserializer);

        private GetManipulationPlanRequest(MessageDeserializer deserializer)
        {
            this.manipulation_plan_request = ManipulationPlanRequestMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.manipulation_plan_request);
        }

        public override string ToString()
        {
            return "GetManipulationPlanRequest: " +
            "\nmanipulation_plan_request: " + manipulation_plan_request.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
