//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.WorldMonitor
{
    [Serializable]
    public class GetAttachedObjectResponse : Message
    {
        public const string k_RosMessageName = "world_monitor/GetAttachedObject";
        public override string RosMessageName => k_RosMessageName;

        public string attached_object_name;

        public GetAttachedObjectResponse()
        {
            this.attached_object_name = "";
        }

        public GetAttachedObjectResponse(string attached_object_name)
        {
            this.attached_object_name = attached_object_name;
        }

        public static GetAttachedObjectResponse Deserialize(MessageDeserializer deserializer) => new GetAttachedObjectResponse(deserializer);

        private GetAttachedObjectResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.attached_object_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.attached_object_name);
        }

        public override string ToString()
        {
            return "GetAttachedObjectResponse: " +
            "\nattached_object_name: " + attached_object_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
