//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.WorldMonitor
{
    [Serializable]
    public class GetAttachedObjectRequest : Message
    {
        public const string k_RosMessageName = "world_monitor/GetAttachedObject";
        public override string RosMessageName => k_RosMessageName;


        public GetAttachedObjectRequest()
        {
        }
        public static GetAttachedObjectRequest Deserialize(MessageDeserializer deserializer) => new GetAttachedObjectRequest(deserializer);

        private GetAttachedObjectRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetAttachedObjectRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
