//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FetchMoveitConfig
{
    [Serializable]
    public class PosesJointsMsg : Message
    {
        public const string k_RosMessageName = "fetch_moveit_config/PosesJoints";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg poses;
        public float[] joints;

        public PosesJointsMsg()
        {
            this.poses = new Geometry.PoseMsg();
            this.joints = new float[0];
        }

        public PosesJointsMsg(Geometry.PoseMsg poses, float[] joints)
        {
            this.poses = poses;
            this.joints = joints;
        }

        public static PosesJointsMsg Deserialize(MessageDeserializer deserializer) => new PosesJointsMsg(deserializer);

        private PosesJointsMsg(MessageDeserializer deserializer)
        {
            this.poses = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.joints, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.poses);
            serializer.WriteLength(this.joints);
            serializer.Write(this.joints);
        }

        public override string ToString()
        {
            return "PosesJointsMsg: " +
            "\nposes: " + poses.ToString() +
            "\njoints: " + System.String.Join(", ", joints.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
